name: KringPos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  firebase_core: ^2.32.0
  image_picker: ^1.1.1
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  shared_preferences: ^2.2.2
  flutter_material_symbols: ^0.0.4
  path_provider: ^2.0.15
  path: ^1.8.3
  cloudinary_public: ^0.23.1
  camera: ^0.10.5+9
  flutter_feather_icons: ^2.0.0
  firebase_database: ^10.3.7
  google_mlkit_commons: ^0.4.0
  firebase_auth: ^4.16.0
  http: ^0.13.6
  google_mlkit_face_detection: ^0.7.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/search.png
    - assets/sukses.png
    - assets/editname.png
    - assets/right.png
    - assets/hapus.png
    - assets/pgaleri.png
    - assets/pkamera.png
    - assets/profilebesar.png
    - assets/role.png
    - assets/email.png
    - assets/delete.png
    - assets/galeri.png
    - assets/kamera.png
    - assets/bakwan.png
    - assets/search1.png
    - assets/simpan.png
    - assets/keluar.png
    - assets/profiledropdown.png
    - assets/logo.png
    - assets/titik3.png
    - assets/notif.png
    - assets/eye.png
    - assets/rolekasir.png
    - assets/roleowner.png
    - assets/tombolmasuk.png
    - assets/tomboldaftar.png
    - assets/tombolkasir.png
    - assets/tombolowner.png
    - assets/logobesar.png
    - assets/ringbell.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: fonts/PoppinsSemiBold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: fonts/PoppinsMedium.ttf
    - family: AnekBangla-Regular
      fonts:
        - asset: fonts/AnekBangla-Regular.ttf
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-SemiBold.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/kringpos.png"
