// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYTmk8UvpswXViV16mxSP4L1bFLjpZYWk',
    appId: '1:988298721966:web:b128e02e84c2ddaa318b3f',
    messagingSenderId: '988298721966',
    projectId: 'kkkk-be4e1',
    authDomain: 'kkkk-be4e1.firebaseapp.com',
    databaseURL: 'https://kkkk-be4e1-default-rtdb.firebaseio.com',
    storageBucket: 'kkkk-be4e1.firebasestorage.app',
    measurementId: 'G-6KTXCM56EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdbm4FNBaPlCHbKSGksJW88u2IuSww8lg',
    appId: '1:988298721966:android:b274cbf25de59f92318b3f',
    messagingSenderId: '988298721966',
    projectId: 'kkkk-be4e1',
    databaseURL: 'https://kkkk-be4e1-default-rtdb.firebaseio.com',
    storageBucket: 'kkkk-be4e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGoGCkkssT9Q-vhgAJExubyqBYxecmxNI',
    appId: '1:988298721966:ios:ef34f20241ec17da318b3f',
    messagingSenderId: '988298721966',
    projectId: 'kkkk-be4e1',
    databaseURL: 'https://kkkk-be4e1-default-rtdb.firebaseio.com',
    storageBucket: 'kkkk-be4e1.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGoGCkkssT9Q-vhgAJExubyqBYxecmxNI',
    appId: '1:988298721966:ios:ef34f20241ec17da318b3f',
    messagingSenderId: '988298721966',
    projectId: 'kkkk-be4e1',
    databaseURL: 'https://kkkk-be4e1-default-rtdb.firebaseio.com',
    storageBucket: 'kkkk-be4e1.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYTmk8UvpswXViV16mxSP4L1bFLjpZYWk',
    appId: '1:988298721966:web:22d2e09a62257434318b3f',
    messagingSenderId: '988298721966',
    projectId: 'kkkk-be4e1',
    authDomain: 'kkkk-be4e1.firebaseapp.com',
    databaseURL: 'https://kkkk-be4e1-default-rtdb.firebaseio.com',
    storageBucket: 'kkkk-be4e1.firebasestorage.app',
    measurementId: 'G-FYL2N8TKLZ',
  );
}
